### ISSUE TITLE
How to use those filters

### ISSUE THREAD

**Issue by pafnow** [SwiftOnSecurity/SwiftFilter#9]
This look really interesting but I don't understand how to use them.
Any place to start with?

**Comment by mbrtchris** [comment]
pafnow, check out the following link for some basic instructions on using PowerShell to export and import the transport rule sets.
(http://www.azure365pro.com/export-and-import-transport-rules-in-exchange-online/)  I found it easier to create barebones rules that I could export from exchange.  I modified the xml file as needed and imported it back into my exchange env.
